### ISSUE TITLE
Convert []interface{} to specific slice

### ISSUE THREAD

**Issue by saheljalal** [cstockton/go-conv#3]
Is this library supposed to handle this case of a slice of interfaces? If so, I don't think I was able to convert a slice of `[]interface{}` to `[]string`

**Comment by cstockton** [comment]
What code are you using to do the conversion? It should work okay.
```
from := []interface{}{"1.2", "34.5", "-678.9"}
var into []string
conv.Slice(&into, from) // type inferred from the element of `into`
fmt.Printf("Slice:\n  %#v\n    -> %#v\n\n", from, into)
```

**Comment by saheljalal** [comment]
My mistake, I must have been doing something wrong. Thanks!

**Comment by cstockton** [comment]
No worries man glad ya got it working!
